"""
Signal Engine Domain Models - Clean Architecture Implementation

This module contains the domain models and value objects for the signal engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from core.datetime_ist import now_ist
from enum import Enum
from typing import Any


class SignalQuality(Enum):
    """Signal quality levels."""
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"


class TimeFrame(Enum):
    """Time frame enumeration."""
    ONE_MIN = "1MIN"
    FIVE_MIN = "5MIN"
    FIFTEEN_MIN = "15MIN"
    THIRTY_MIN = "30MIN"
    ONE_HOUR = "1HOUR"
    TWO_HOUR = "2HOUR"
    FOUR_HOUR = "4HOUR"
    ONE_DAY = "1DAY"
    ONE_WEEK = "1WEEK"


@dataclass
class TradingSignal:
    """Trading signal generated by the signal engine."""
    symbol: str
    strength: float  # 0.0 to 1.0
    direction: str   # "BUY", "SELL", or "NEUTRAL"
    quality: SignalQuality = SignalQuality.WEAK
    timestamp: datetime = None
    signal_type: str = "TECHNICAL"  # TECHNICAL, ML, COMBINED, etc.
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = now_ist()

    def is_valid(self) -> bool:
        """Validate the trading signal.

        Returns:
            True if the signal is valid, False otherwise
        """
        # Basic validation: strength between 0 and 1, direction is BUY or SELL
        if not (0.0 <= self.strength <= 1.0):
            return False
        if self.direction not in ["BUY", "SELL"]:
            return False
        return True


@dataclass
class MarketData:
    """Market data structure."""
    symbol: str
    candles: list = field(default_factory=list)
    timestamp: datetime = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = now_ist()


@dataclass
class Candle:
    """OHLCV candle data."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int


@dataclass
class TechnicalIndicators:
    """Technical indicator values."""
    sma_20: float | None = None
    sma_50: float | None = None
    ema_12: float | None = None
    ema_26: float | None = None
    macd: float | None = None
    macd_signal: float | None = None
    macd_histogram: float | None = None
    rsi: float | None = None
    bb_upper: float | None = None
    bb_middle: float | None = None
    bb_lower: float | None = None
    atr: float | None = None
    adx: float | None = None
    stoch_k: float | None = None
    stoch_d: float | None = None
    obv: float | None = None
    vwap: float | None = None


@dataclass
class MarketConditions:
    """Current market conditions."""
    volatility: float = 0.0
    liquidity: str = "NORMAL"  # HIGH, NORMAL, LOW
    trend: str = "NEUTRAL"     # BULLISH, BEARISH, NEUTRAL
    volume_profile: str = "NORMAL"  # HIGH, NORMAL, LOW


@dataclass
class OrderFlowData:
    """Order flow data structure."""
    bid_volume: float = 0.0
    ask_volume: float = 0.0
    volume_imbalance: float = 0.0
    large_buy_orders: int = 0
    large_sell_orders: int = 0
    trade_frequency: float = 0.0


@dataclass
class SentimentData:
    """Sentiment data structure."""
    news_sentiment: float = 0.0  # -1 to 1
    social_sentiment: float = 0.0  # -1 to 1
    put_call_ratio: float = 0.0
    vix_level: float = 0.0
    fear_greed_index: float = 0.0  # 0 to 100


# Value objects
@dataclass(frozen=True)
class PriceLevel:
    """Immutable price level."""
    price: float
    timestamp: datetime


@dataclass(frozen=True)
class VolumeProfile:
    """Immutable volume profile."""
    volume_node: float
    price_level: PriceLevel
    timestamp: datetime
