"""
Signal Approval Workflow (v2.46 Sprint 1B).

Defines how auto-generated and manual signals are routed:
  SIGNALS_ONLY      — generate + notify, NO execution (default — safest)
  MANUAL_PRIORITY   — manual→PENDING queue; STRONG auto; MODERATE→PENDING
  FULL_MANUAL       — ALL signals → PENDING queue regardless of tier
  AUTO_WITH_OVERRIDE — auto-execute, manual gets priority + insertion window
  FULLY_AUTO        — all signals execute; manual injects directly (broker must be live)

Only SIGNALS_ONLY and FULL_MANUAL modes are enabled in config by default.
FULLY_AUTO requires EXECUTION_MODE=AUTO + BROKER_API_ENABLED=true explicitly.

Public API
----------
    SignalDecision        — result dataclass
    SignalApprovalWorkflow — evaluates each signal and returns a SignalDecision
    build_workflow(cfg, queue) → SignalApprovalWorkflow

Config keys
-----------
    manual_signal_workflow_mode  : str  default "SIGNALS_ONLY"
    manual_signal_min_score      : int  default 50
    manual_signal_max_score      : int  default 100
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

_log = logging.getLogger(__name__)

# ── Workflow modes ─────────────────────────────────────────────────────────────

SIGNALS_ONLY       = "SIGNALS_ONLY"
MANUAL_PRIORITY    = "MANUAL_PRIORITY"
FULL_MANUAL        = "FULL_MANUAL"
AUTO_WITH_OVERRIDE = "AUTO_WITH_OVERRIDE"
FULLY_AUTO         = "FULLY_AUTO"

_ALL_MODES = {SIGNALS_ONLY, MANUAL_PRIORITY, FULL_MANUAL, AUTO_WITH_OVERRIDE, FULLY_AUTO}

# ── Actions ────────────────────────────────────────────────────────────────────

EXECUTE      = "EXECUTE"       # proceed to entry gate immediately
QUEUE        = "QUEUE"         # add to ManualSignalQueue (PENDING)
NOTIFY_ONLY  = "NOTIFY_ONLY"   # send Telegram alert, no execution
SKIP         = "SKIP"          # silently drop


# ── Signal types ───────────────────────────────────────────────────────────────

SIG_AUTO   = "AUTO"    # generated by scan engine
SIG_MANUAL = "MANUAL"  # submitted via Telegram / dashboard / CSV


@dataclass
class SignalDecision:
    action:               str              # EXECUTE | QUEUE | NOTIFY_ONLY | SKIP
    priority:             int   = 1        # 0=CRITICAL, 1=HIGH, 2=NORMAL
    notify_channels:      list[str] = field(default_factory=lambda: ["TELEGRAM"])
    execution_delay_secs: int   = 0
    queue_signal_id:      str | None = None   # set when action=QUEUE
    reason:               str  = ""

    @property
    def should_execute(self) -> bool:
        return self.action == EXECUTE

    @property
    def should_queue(self) -> bool:
        return self.action == QUEUE

    @property
    def should_notify(self) -> bool:
        return self.action in (EXECUTE, NOTIFY_ONLY, QUEUE)


# ── Workflow ───────────────────────────────────────────────────────────────────

class SignalApprovalWorkflow:
    """
    Determines what happens to each incoming signal.

    Call process_signal() for every signal — returns a SignalDecision
    that tells the caller what to do next.
    """

    def __init__(self, cfg: dict[str, Any], queue=None) -> None:
        raw_mode = str(cfg.get("manual_signal_workflow_mode", SIGNALS_ONLY)).upper()
        if raw_mode not in _ALL_MODES:
            _log.warning("[WORKFLOW] Unknown mode %r — defaulting to SIGNALS_ONLY", raw_mode)
            raw_mode = SIGNALS_ONLY
        self._mode = raw_mode
        self._queue = queue  # ManualSignalQueue | None
        self._min_score = int(cfg.get("manual_signal_min_score", 50))
        self._max_score = int(cfg.get("manual_signal_max_score", 100))
        # Tier thresholds (read from config so they stay in sync with pipeline)
        self._strong_min   = int(cfg.get("TIER_STRONG_MIN",   80))
        self._moderate_min = int(cfg.get("TIER_MODERATE_MIN", 70))
        # Live-path-risk guard
        self._broker_api_enabled = bool(cfg.get("BROKER_API_ENABLED", False))
        self._execution_mode = str(cfg.get("EXECUTION_MODE", "MANUAL")).upper()
        _log.info("[WORKFLOW] Mode=%s broker_api=%s exec=%s",
                  self._mode, self._broker_api_enabled, self._execution_mode)

    @property
    def mode(self) -> str:
        return self._mode

    def process_signal(
        self,
        signal_type: str,          # SIG_AUTO | SIG_MANUAL
        score: int,
        tier: str = "",            # STRONG | MODERATE | WEAK
        index_name: str = "",
        direction: str = "",
        reason: str = "",
        analyst_name: str = "AUTO",
        manual_signal_id: str | None = None,
        source: str = "ENGINE",
    ) -> SignalDecision:
        """
        Evaluate a signal and return a SignalDecision.

        Args:
            signal_type:       SIG_AUTO (engine-generated) or SIG_MANUAL (human)
            score:             0-100 signal score
            tier:              STRONG | MODERATE | WEAK
            index_name:        NIFTY | BANKNIFTY | FINNIFTY
            direction:         CALL | PUT
            reason:            human-readable signal summary
            analyst_name:      who submitted (for SIG_MANUAL)
            manual_signal_id:  pre-assigned ID (for SIG_MANUAL already in queue)
            source:            SOURCE label for audit

        Returns:
            SignalDecision
        """
        effective_tier = tier.upper() if tier else self._score_to_tier(score)
        is_manual = signal_type == SIG_MANUAL

        if self._mode == SIGNALS_ONLY:
            return self._decide_signals_only(is_manual, score, effective_tier, index_name, direction, analyst_name, reason)

        if self._mode == FULL_MANUAL:
            return self._decide_full_manual(is_manual, score, index_name, direction, analyst_name, reason, manual_signal_id)

        if self._mode == MANUAL_PRIORITY:
            return self._decide_manual_priority(is_manual, score, effective_tier, index_name, direction, analyst_name, reason, manual_signal_id)

        if self._mode == AUTO_WITH_OVERRIDE:
            return self._decide_auto_with_override(is_manual, score, effective_tier, index_name, direction, analyst_name, reason)

        if self._mode == FULLY_AUTO:
            return self._decide_fully_auto(is_manual, score, effective_tier, index_name, direction, analyst_name, reason)

        return SignalDecision(action=NOTIFY_ONLY, reason="Unknown workflow mode")

    # ── Mode implementations ───────────────────────────────────────────────

    def _decide_signals_only(self, is_manual, score, tier, index_name, direction, analyst, reason) -> SignalDecision:
        """SIGNALS_ONLY: always notify, never execute."""
        priority = 1 if tier == "STRONG" else 2
        return SignalDecision(
            action=NOTIFY_ONLY,
            priority=priority,
            notify_channels=["TELEGRAM"],
            reason=f"SIGNALS_ONLY mode — notify only (score={score} tier={tier})",
        )

    def _decide_full_manual(self, is_manual, score, index_name, direction, analyst, reason, existing_id) -> SignalDecision:
        """FULL_MANUAL: every signal goes to approval queue."""
        if score < self._min_score:
            return SignalDecision(action=SKIP, reason=f"Score {score} < min {self._min_score}")
        if self._queue is None:
            return SignalDecision(action=NOTIFY_ONLY, reason="Queue unavailable — notify only")
        if existing_id:
            return SignalDecision(action=QUEUE, queue_signal_id=existing_id,
                                  reason="Full manual — existing signal queued")
        sig = self._queue.submit(index_name, direction, score, reason,
                                 source="ENGINE" if not is_manual else "TELEGRAM",
                                 analyst_name=analyst)
        return SignalDecision(action=QUEUE, queue_signal_id=sig.signal_id,
                              reason=f"Full manual — queued as {sig.signal_id}")

    def _decide_manual_priority(self, is_manual, score, tier, index_name, direction, analyst, reason, existing_id) -> SignalDecision:
        """MANUAL_PRIORITY: manual→queue; STRONG→execute; MODERATE→queue."""
        if is_manual:
            return self._decide_full_manual(is_manual, score, index_name, direction, analyst, reason, existing_id)
        if score < self._min_score:
            return SignalDecision(action=SKIP, reason=f"Score {score} < min {self._min_score}")
        if tier == "STRONG" and self._can_execute():
            return SignalDecision(action=EXECUTE, priority=0,
                                  reason=f"MANUAL_PRIORITY: STRONG auto-execute (score={score})")
        if tier == "MODERATE" and self._queue is not None:
            sig = self._queue.submit(index_name, direction, score, reason,
                                     source="ENGINE", analyst_name="AUTO_MODERATE")
            return SignalDecision(action=QUEUE, queue_signal_id=sig.signal_id, priority=1,
                                  reason=f"MANUAL_PRIORITY: MODERATE queued (score={score})")
        return SignalDecision(action=NOTIFY_ONLY, priority=2,
                              reason=f"MANUAL_PRIORITY: WEAK notify only (score={score})")

    def _decide_auto_with_override(self, is_manual, score, tier, index_name, direction, analyst, reason) -> SignalDecision:
        """AUTO_WITH_OVERRIDE: auto executes; manual signal gets priority insertion."""
        if is_manual and self._can_execute():
            return SignalDecision(action=EXECUTE, priority=0, execution_delay_secs=0,
                                  reason=f"Manual override — priority execute (score={score})")
        if score < self._min_score:
            return SignalDecision(action=NOTIFY_ONLY, reason=f"Score {score} < min {self._min_score}")
        if self._can_execute():
            return SignalDecision(action=EXECUTE, priority=1,
                                  reason=f"AUTO_WITH_OVERRIDE: auto execute (score={score} tier={tier})")
        return SignalDecision(action=NOTIFY_ONLY, reason="Cannot execute — broker unavailable")

    def _decide_fully_auto(self, is_manual, score, tier, index_name, direction, analyst, reason) -> SignalDecision:
        """FULLY_AUTO: all signals execute directly (requires live broker)."""
        if not self._can_execute():
            return SignalDecision(action=NOTIFY_ONLY,
                                  reason="FULLY_AUTO: broker not enabled — notify only")
        if score < self._min_score:
            return SignalDecision(action=SKIP, reason=f"Score {score} < min {self._min_score}")
        return SignalDecision(action=EXECUTE, priority=0 if is_manual else 1,
                              reason=f"FULLY_AUTO: execute (score={score} tier={tier})")

    # ── Helpers ────────────────────────────────────────────────────────────

    def _can_execute(self) -> bool:
        """True only when broker is live-capable and enabled."""
        return self._broker_api_enabled and self._execution_mode in ("AUTO", "LIVE")

    def _score_to_tier(self, score: int) -> str:
        if score >= self._strong_min:
            return "STRONG"
        if score >= self._moderate_min:
            return "MODERATE"
        return "WEAK"


# ── Factory ────────────────────────────────────────────────────────────────────

def build_workflow(cfg: dict[str, Any], queue=None) -> SignalApprovalWorkflow:
    """Build a SignalApprovalWorkflow from config."""
    try:
        return SignalApprovalWorkflow(cfg, queue)
    except Exception as exc:
        _log.error("[WORKFLOW] Init failed: %s", exc)
        return SignalApprovalWorkflow({"manual_signal_workflow_mode": SIGNALS_ONLY}, None)
