"""
Shared Models

This module contains shared domain models used across the trading platform,
such as Order, Position, Quote, and Signal.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class Order:
    """
    Trading order specification.

    Attributes:
        symbol: The trading symbol (e.g., "NIFTY26JULFUT")
        direction: "BUY" or "SELL"
        quantity: Number of lots/contracts
        order_type: Type of order (MARKET, LIMIT, SL, SL-M)
        price: Limit price (for LIMIT orders) or trigger price (for SL/SL-M)
        strategy_id: Identifier of the strategy that generated this order
        order_id: Optional broker-assigned order ID
        timestamp: When the order was created
    """

    symbol: str
    direction: str  # "BUY" or "SELL"
    quantity: int
    order_type: str = "MARKET"  # MARKET, LIMIT, SL, SL-M
    price: float | None = None
    trigger_price: float | None = None  # For SL and SL-M orders
    strategy_id: str = ""
    order_id: str | None = None
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class OrderResult:
    """
    Result of order execution.

    Attributes:
        order_id: The order ID returned by the broker
        status: Order status (OPEN, FILLED, PARTIALLY_FILLED, CANCELLED, REJECTED, ERROR)
        filled_quantity: Quantity that has been filled
        average_price: Average fill price
        commission: Commission charged by the broker
        timestamp: When the result was recorded
        reject_reason: Reason for rejection (if applicable)
    """

    order_id: str
    status: str  # OPEN, FILLED, PARTIALLY_FILLED, CANCELLED, REJECTED, ERROR
    filled_quantity: int = 0
    average_price: float = 0.0
    commission: float = 0.0
    timestamp: datetime = field(default_factory=datetime.now)
    reject_reason: str | None = None


@dataclass
class Position:
    """
    Trading position.

    Attributes:
        symbol: The trading symbol
        quantity: Position size (positive for long, negative for short)
        average_price: Average entry price
        market_value: Current market value of the position
        unrealized_pnl: Unrealized profit/loss
        realized_pnl: Realized profit/loss
        timestamp: When the position was last updated
    """

    symbol: str
    quantity: int  # Positive for long, negative for short
    average_price: float
    market_value: float
    unrealized_pnl: float
    realized_pnl: float
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Quote:
    """
    Market quote.

    Attributes:
        symbol: Trading symbol
        bid: Best bid price
        ask: Best ask price
        last: Last traded price
        volume: Trading volume
        timestamp: When the quote was received
    """

    symbol: str
    bid: float
    ask: float
    last: float
    volume: int
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Fill:
    """
    Order fill/execution.

    Attributes:
        order_id: The order ID that was filled
        symbol: The trading symbol
        quantity: Quantity filled
        price: Fill price
        timestamp: When the fill occurred
        commission: Commission charged for this fill
    """

    order_id: str
    symbol: str
    quantity: int
    price: float
    timestamp: datetime = field(default_factory=datetime.now)
    commission: float = 0.0


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Attributes:
        symbol: The trading symbol
        direction: "BUY" or "SELL"
        strength: Signal strength (typically 0.0 to 1.0)
        confidence: Confidence in the signal (0.0 to 1.0)
        strategy_id: ID of the strategy that generated the signal
        timestamp: When the signal was generated
        metadata: Additional signal-specific data
    """

    symbol: str
    direction: str  # "BUY" or "SELL"
    strength: float = 0.0  # 0.0 to 1.0
    confidence: float = 0.0  # 0.0 to 1.0
    strategy_id: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict[str, Any] = field(default_factory=dict)


# Export all models
__all__ = [
    "Order",
    "OrderResult",
    "Position",
    "Quote",
    "Fill",
    "Signal",
]
