"""Constants for the AD-KIYU Auth Handler."""

from __future__ import annotations

HASH_ALGO = "sha256"
PBKDF2_ITERATIONS = 600000
SALT_BYTES = 32
TOKEN_BYTES = 48
TOKEN_TTL_SECONDS = 3600  # 1 hour
REFRESH_TTL_SECONDS = 86400 * 7  # 7 days
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_SECONDS = 900  # 15 minutes
BRUTE_FORCE_WINDOW_SECONDS = 60
BRUTE_FORCE_MAX_ATTEMPTS = 10
MAX_CONCURRENT_SESSIONS = 10
SESSION_COOKIE_NAME = "opb_session"
CSRF_COOKIE_NAME = "opb_csrf"
CSRF_HEADER_NAME = "X-CSRF-Token"
MIN_PASSWORD_LENGTH = 8
DEFAULT_ADMIN_USERNAME = "admin"
