#!/usr/bin/env python3
"""Coverage Heatmap Generator — OPB v2.57.0

Generates coverage heatmaps from pytest-cov data showing:
  - Coverage by module directory
  - Coverage by file (top-level)
  - Coverage by critical path (risk, execution, broker, etc.)
  - Overall coverage trend over time

Usage:
    # First run coverage:
    python -m pytest tests/ --cov=core --cov-report=json:coverage_json.json

    # Then generate heatmap:
    python scripts/run_coverage_heatmap.py
    python scripts/run_coverage_heatmap.py --json
    python scripts/run_coverage_heatmap.py --ci

Requires:
    - coverage JSON data (coverage_json.json or .coverage)
    - pytest-cov installed
"""

from __future__ import annotations

import json
import os
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

# ── Configuration ─────────────────────────────────────────────────────────────

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"
HTML_REPORT = REPORTS_DIR / "coverage_heatmap.html"
JSON_REPORT = REPORTS_DIR / "coverage_heatmap.json"
COVERAGE_JSON = "coverage_json.json"
COVERAGE_THRESHOLD = 90  # Target coverage percentage
CRITICAL_PATH_MIN_COVERAGE = 95  # Critical paths must exceed this

CRITICAL_PATHS = {
    "risk": [
        "core/services/risk_service.py",
        "core/kelly_sizer.py",
        "core/var_calculator.py",
        "core/stress_tester.py",
        "core/reentry_evaluator.py",
        "core/liquidity_guard.py",
        "core/correlation_guard.py",
        "core/safety_state.py",
        "core/safety_engine.py",
    ],
    "execution": [
        "core/execution/idempotency/certifier.py",
        "core/wal/journal.py",
        "core/broker_failover.py",
        "core/state_manager.py",
    ],
    "broker": [
        "core/adapters/broker_adapters.py",
        "core/services/paper_trader.py",
    ],
    "signal": [
        "core/adaptive_signal.py",
        "core/pure_index_signal.py",
        "core/strike_selector.py",
        "core/tier_engine.py",
    ],
    "ml": [
        "core/ml_classifier.py",
        "core/ml_performance_tracker.py",
        "core/concept_drift_detector.py",
    ],
    "governance": [
        "core/constitution.py",
        "core/constitution_ai_gate.py",
        "core/environment.py",
    ],
    "security": [
        "core/security_auditor.py",
        "core/runtime_security.py",
        "core/threat_modeler.py",
    ],
    "startup": [
        "core/startup.py",
        "core/startup_checklist.py",
        "core/startup_validation.py",
    ],
}

COVERAGE_HISTORY_FILE = REPORTS_DIR / "coverage_history.json"


def load_coverage_data(path: str = COVERAGE_JSON) -> dict[str, Any] | None:
    """Load coverage data from JSON file generated by pytest-cov."""
    if os.path.exists(path):
        try:
            return json.loads(Path(path).read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return None


def _get_file_coverage(files: dict[str, Any], filepath: str) -> dict[str, Any] | None:
    """Get coverage for a specific file path."""
    # Normalize path separators — use endswith to avoid false substring matches
    norm_path = filepath.replace("\\", "/")
    for path, data in files.items():
        normalized = path.replace("\\", "/")
        if normalized == norm_path or normalized.endswith("/" + norm_path):
            return data
    return None


def generate_heatmap(cov_data: dict[str, Any]) -> dict[str, Any]:
    """Generate coverage heatmap from coverage data."""
    files = cov_data.get("files", {})
    if not files:
        return {"error": "No coverage data found. Run: python -m pytest --cov=core --cov-report=json:coverage_json.json"}

    # Overall stats
    total_statements = 0
    total_covered = 0
    file_coverage: list[dict[str, Any]] = []

    for filepath, data in files.items():
        summary = data.get("summary", data)
        statements = summary.get("num_statements", 0)
        covered = summary.get("covered_lines", 0) or summary.get("num_covered", 0)
        missing = summary.get("missing_lines", 0) or summary.get("num_missing", 0)

        total_statements += statements
        total_covered += covered

        pct = (covered / statements * 100) if statements > 0 else 0
        file_coverage.append({
            "file": filepath,
            "statements": statements,
            "covered": covered,
            "missing": missing,
            "coverage_pct": round(pct, 1),
        })

    overall_pct = (total_covered / total_statements * 100) if total_statements > 0 else 0

    # Coverage by module directory
    module_coverage: dict[str, dict[str, float | int]] = defaultdict(lambda: {"statements": 0, "covered": 0})
    for fc in file_coverage:
        parts = fc["file"].replace("\\", "/").split("/")
        module = parts[0] if parts else "other"
        module_coverage[module]["statements"] += fc["statements"]
        module_coverage[module]["covered"] += fc["covered"]

    module_results = {}
    for module, data in module_coverage.items():
        pct = (data["covered"] / data["statements"] * 100) if data["statements"] > 0 else 0
        module_results[module] = {
            "statements": data["statements"],
            "covered": data["covered"],
            "coverage_pct": round(pct, 1),
        }

    # Coverage by critical path
    critical_results = {}
    critical_passed = True
    for path_name, path_files in CRITICAL_PATHS.items():
        path_stats = {"statements": 0, "covered": 0, "files_found": 0, "files_missing": 0}
        for pf in path_files:
            fc = _get_file_coverage(files, pf)
            if fc:
                s = fc.get("summary", fc)
                path_stats["statements"] += s.get("num_statements", 0)
                path_stats["covered"] += s.get("covered_lines", 0) or s.get("num_covered", 0)
                path_stats["files_found"] += 1
            else:
                path_stats["files_missing"] += 1

        pct = (path_stats["covered"] / path_stats["statements"] * 100) if path_stats["statements"] > 0 else 0
        path_ok = pct >= CRITICAL_PATH_MIN_COVERAGE
        if not path_ok:
            critical_passed = False

        critical_results[path_name] = {
            "statements": path_stats["statements"],
            "covered": path_stats["covered"],
            "coverage_pct": round(pct, 1),
            "files_found": path_stats["files_found"],
            "files_missing": path_stats["files_missing"],
            "minimum_required": CRITICAL_PATH_MIN_COVERAGE,
            "passed": path_ok,
        }

    # Sort file coverage by coverage (ascending = worst first)
    file_coverage.sort(key=lambda x: x["coverage_pct"])

    return {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S IST"),
        "version": "2.57.0",
        "overall": {
            "total_statements": total_statements,
            "total_covered": total_covered,
            "total_missing": total_statements - total_covered,
            "coverage_pct": round(overall_pct, 1),
            "target_threshold": COVERAGE_THRESHOLD,
            "threshold_met": overall_pct >= COVERAGE_THRESHOLD,
        },
        "by_module": module_results,
        "by_file": file_coverage,
        "critical_paths": critical_results,
        "critical_paths_all_passed": critical_passed,
    }


def _generate_html(heatmap: dict[str, Any]) -> str:
    """Generate HTML visualization of coverage heatmap."""
    if "error" in heatmap:
        return f"<html><body><h1>Error</h1><p>{heatmap['error']}</p></body></html>"

    overall = heatmap["overall"]
    timestamp = heatmap.get("timestamp", "")

    # Overall score
    overall_class = "good" if overall["coverage_pct"] >= 90 else "moderate" if overall["coverage_pct"] >= 80 else "poor"

    # Module rows
    module_rows = ""
    for module in sorted(heatmap["by_module"].keys()):
        m = heatmap["by_module"][module]
        color = "#4CAF50" if m["coverage_pct"] >= 90 else "#FF9800" if m["coverage_pct"] >= 80 else "#f44336"
        bar_width = max(2, m["coverage_pct"] * 0.8)
        module_rows += f"""
        <tr>
            <td><strong>{module}</strong></td>
            <td>{m['statements']}</td>
            <td>{m['coverage_pct']}%</td>
            <td><div style="background:{color};height:20px;width:{bar_width}px;border-radius:3px;min-width:2px;"></div></td>
        </tr>"""

    # Critical path rows
    critical_rows = ""
    for path_name in sorted(heatmap["critical_paths"].keys()):
        cp = heatmap["critical_paths"][path_name]
        icon = "✅" if cp["passed"] else "❌"
        color = "#4CAF50" if cp["passed"] else "#f44336"
        bar_width = max(2, cp["coverage_pct"] * 0.8)
        critical_rows += f"""
        <tr>
            <td>{icon}</td>
            <td><strong>{path_name}</strong></td>
            <td>{cp['statements']}</td>
            <td>{cp['coverage_pct']}%</td>
            <td>{cp['minimum_required']}%</td>
            <td><div style="background:{color};height:20px;width:{bar_width}px;border-radius:3px;min-width:2px;"></div></td>
        </tr>"""

    # Bottom 20 files (worst coverage)
    worst_files = heatmap["by_file"][:20]
    file_rows = ""
    for fc in worst_files:
        file_rows += f"""
        <tr>
            <td>{fc['file']}</td>
            <td>{fc['statements']}</td>
            <td>{fc['covered']}</td>
            <td>{fc['missing']}</td>
            <td style="color:{'red' if fc['coverage_pct'] < 80 else 'orange' if fc['coverage_pct'] < 90 else 'green'}">{fc['coverage_pct']}%</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Coverage Heatmap — OPB v2.57.0</title>
<style>
body {{ font-family: -apple-system, sans-serif; margin: 20px; background: #f5f5f5; }}
h1, h2, h3 {{ color: #333; }}
table {{ border-collapse: collapse; width: 100%; margin: 10px 0 20px; background: #fff; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
th {{ background: #4A90D9; color: white; }}
tr:nth-child(even) {{ background: #f9f9f9; }}
.overall {{ font-size: 48px; font-weight: bold; text-align: center; padding: 20px; }}
.good {{ color: #4CAF50; }}
.moderate {{ color: #FF9800; }}
.poor {{ color: #f44336; }}
.summary {{ background: #e8f5e9; padding: 15px; border-radius: 5px; margin: 10px 0; }}
.passed {{ color: #4CAF50; font-weight: bold; }}
.failed {{ color: #f44336; font-weight: bold; }}
</style>
</head>
<body>
<h1>📊 Coverage Heatmap — OPB v2.57.0</h1>
<div class="summary">
<p><strong>Timestamp:</strong> {timestamp}</p>
<p><strong>Threshold:</strong> {overall['target_threshold']}%</p>
</div>

<div class="overall {overall_class}">
    {overall['coverage_pct']}%
    <div style="font-size: 16px;">
        {overall['total_covered']} / {overall['total_statements']} statements covered
        ({overall['total_missing']} missing)
    </div>
    <div style="font-size: 16px;">
        Threshold: {'✅ MET' if overall['threshold_met'] else '❌ NOT MET'} ({overall['target_threshold']}%)
    </div>
</div>

<h2>📁 Coverage by Module</h2>
<table>
<tr><th>Module</th><th>Statements</th><th>Coverage</th><th>Visual</th></tr>
{module_rows}
</table>

<h2>🛡️ Critical Path Coverage</h2>
<table>
<tr><th>Status</th><th>Path</th><th>Statements</th><th>Coverage</th><th>Required</th><th>Visual</th></tr>
{critical_rows}
</table>
<p>Critical paths all ≥{CRITICAL_PATH_MIN_COVERAGE}%: <span class="{'passed' if heatmap['critical_paths_all_passed'] else 'failed'}">{'✅ PASSED' if heatmap['critical_paths_all_passed'] else '❌ FAILED'}</span></p>

<h2>⚠️ Lowest Coverage Files (Top 20)</h2>
<table>
<tr><th>File</th><th>Statements</th><th>Covered</th><th>Missing</th><th>Coverage %</th></tr>
{file_rows}
</table>

<p style="color:#888; margin-top:30px;">Generated by OPB Coverage Heatmap v2.57.0</p>
</body>
</html>"""
    return html


def _load_history() -> dict:
    """Load previous coverage history."""
    if COVERAGE_HISTORY_FILE.exists():
        try:
            return json.loads(COVERAGE_HISTORY_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {"history": []}


def _save_history(heatmap: dict[str, Any]) -> None:
    """Save coverage snapshot to history."""
    history = _load_history()
    history.setdefault("history", []).append({
        "timestamp": heatmap.get("timestamp", ""),
        "overall_pct": heatmap.get("overall", {}).get("coverage_pct", 0),
    })
    # Keep last 100 entries
    history["history"] = history["history"][-100:]
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    COVERAGE_HISTORY_FILE.write_text(json.dumps(history, indent=2), encoding="utf-8")


def main() -> int:
    """CLI entry point."""
    import argparse
    parser = argparse.ArgumentParser(description="Coverage Heatmap Generator")
    parser.add_argument("--json", action="store_true", help="Output JSON report")
    parser.add_argument("--no-html", action="store_true", help="Skip HTML generation")
    parser.add_argument("--ci", action="store_true", help="CI mode: exit non-zero if thresholds not met")
    parser.add_argument("--input", default=COVERAGE_JSON, help="Coverage JSON input file")
    args = parser.parse_args()

    os.makedirs(REPORTS_DIR, exist_ok=True)

    print("=" * 60)
    print("  COVERAGE HEATMAP GENERATOR v2.57.0")
    print("=" * 60)

    cov_data = load_coverage_data(args.input)
    if not cov_data:
        print("\n❌ No coverage data found.")
        print("\nRun coverage first:")
        print("  python -m pytest tests/ --cov=core --cov-report=json:coverage_json.json")
        print("  python scripts/run_coverage_heatmap.py")
        return 1

    heatmap = generate_heatmap(cov_data)

    if args.json:
        print(json.dumps(heatmap, indent=2, default=str))

    if not args.no_html:
        html = _generate_html(heatmap)
        HTML_REPORT.write_text(html, encoding="utf-8")
        print(f"\n  HTML report: {HTML_REPORT}")

    JSON_REPORT.write_text(json.dumps(heatmap, indent=2, default=str), encoding="utf-8")
    print(f"  JSON report: {JSON_REPORT}")

    # Save to history
    _save_history(heatmap)

    # Print summary
    o = heatmap["overall"]
    print(f"\n  Overall Coverage: {o['coverage_pct']}%")
    print(f"  Threshold ({o['target_threshold']}%): {'✅ MET' if o['threshold_met'] else '❌ NOT MET'}")

    print("\n  Critical Paths:")
    for path_name, cp in heatmap["critical_paths"].items():
        icon = "✅" if cp["passed"] else "❌"
        print(f"    {icon} {path_name:<15s} {cp['coverage_pct']}% (required: {cp['minimum_required']}%)")

    if not heatmap["critical_paths_all_passed"]:
        print("\n  ⚠️  Some critical paths below minimum coverage threshold!")

    if args.ci:
        if not o["threshold_met"]:
            print(f"\n❌ CI FAILED: Coverage {o['coverage_pct']}% < {o['target_threshold']}%")
            return 1
        if not heatmap["critical_paths_all_passed"]:
            print(f"\n❌ CI FAILED: Critical paths below {CRITICAL_PATH_MIN_COVERAGE}% coverage")
            return 1

    print("\n" + "=" * 60)
    print("  COVERAGE HEATMAP COMPLETE")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
